Repository maple-labs/maple-proxy-factory, pull requests merged in 2021-12, with the labels that each got.

#16 fix: Use shorter requires (C4 #3)
  contracts/MapleProxyFactory.sol
Labels: Priority: High, Status: Ready for Review

#17 fix: Lock pragma (C4 #23)
  contracts/MapleProxied.sol
  contracts/MapleProxyFactory.sol
  contracts/interfaces/IMapleProxied.sol
  contracts/interfaces/IMapleProxyFactory.sol
  contracts/interfaces/Interfaces.sol
  contracts/test/MapleProxyFactory.t.sol
  contracts/test/accounts/User.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: High, Status: Ready for Review

#18 fix: Update Natspec typo (C4 #22)
  contracts/interfaces/IMapleProxied.sol
Labels: Priority: High, Status: Ready for Review

#19 feat: Add globals validation and test (C4 #13)
  contracts/MapleProxyFactory.sol
  contracts/test/MapleProxyFactory.t.sol
Labels: Priority: High, Status: Ready for Review

#20 chore: Cleanup
  contracts/MapleProxyFactory.sol
Labels: Priority: Medium, Status: Ready for Review

#25 Fix: Label for section (SC-4288)
  contracts/MapleProxyFactory.sol
Labels: Priority: Low, Status: Ready for Review

#26 formatting: Solc, imports, underscores
  contracts/MapleProxyFactory.sol
  contracts/interfaces/IMapleProxyFactory.sol
  contracts/test/MapleProxyFactory.t.sol
  contracts/test/accounts/User.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: High, Status: Ready for Review
