Repository maple-labs/maple-proxy-factory, pull requests merged in 2021-11, with the labels that each got.

#4 feat: Add README
  README.md
Labels: Priority: High, Status: Ready for Review

#6 feat: Public functions
  contracts/MapleProxyFactory.sol
Labels: Priority: High, Status: Ready for Review

#11 fix: Update EmptyContract
  contracts/test/MapleProxyFactory.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#12 chore: CEI (event emissions before interactions, where possible) (SC-4189)
  contracts/MapleProxyFactory.sol
Labels: Priority: Medium, Status: Ready for Merge, Status: On Hold
